/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini.project.sem4;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import dataacess.ProductDataAccess;
import dataacess.billdoa;
import java.io.File;
import java.io.FileOutputStream;
import java.util.Iterator;
import model.Product;
import java.lang.String;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Bill;

/**
 *
 * @author madhurshinde
 */
public class billingpage extends javax.swing.JFrame {
    public int billId=1;
    public int totalll=0;
    public int productPrice=0;
    public int productTotal=0;
    public int gst=0;
    public int grandtotal;
    public int productQuantity=0;
   //  private int lastGeneratedBillId = 0;
            
    

    /**
     * Creates new form billingpage
     */
    public billingpage() {
        initComponents();
           dt();
        times();
    }

 
      public billingpage(String email) {
        initComponents();
        dt();
        times();
        txtProductname.setEditable(false);
       txtPoductprice.setEnabled(false);
       txtTotal.setEditable(false);
       btnADDtcart.setEnabled(false);
       btnGeneartebillp.setEnabled(false);
       JFormattedTextField tf=((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
       tf.setEditable(false);
       
    }

  public void dt() {
      Date d=new Date();
      SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
      String dd= sdf.format(d);
      l_date.setText(dd);
         
  
  }
   Timer t;
  SimpleDateFormat st;
  public void times(){
 
    t = new Timer(1000, new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
         // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
          Date dt=new Date();
           
           st= new SimpleDateFormat("hh:mm:ss a");
           String tt=st.format(dt);
           l_time.setText(tt);
      }
  });
    t.start();
  }
  
public void filterProductBYname(String name) {
    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
    dtm.setRowCount(0);
    ArrayList<Product> list = ProductDataAccess.getAllRecords();
    Iterator<Product> itr = list.iterator();
    while (itr.hasNext()) {
        Product productObj = itr.next();
        dtm.addRow(new Object[]{productObj.getName(), productObj.getPrice()});
    }
}

  
  

  
  public void clearProductFields(){
txtProductname.setText("");
       txtPoductprice.setText("");
       jSpinner1.setValue(1);
       txtTotal.setText("");
       btnADDtcart.setEnabled(false);
  
  
  }
  public void validatefields()
  {
btnGeneartebillp.setEnabled(true);
  
  }
  private void performSearchAndUpdate(String name) {
    filterProductBYname(name);
}

private void initializeProductList() {
    performSearchAndUpdate(""); // Show all products initially
}
private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
    performSearchAndUpdate(txtSearch.getText()); // Call search when the search button is clicked
}
    public void calculateGST() {
        // Assuming GST is 18% of the total amount
        double gstPercentage = 0.18;
        gst = (int) (totalll * gstPercentage);
       lblgst.setText(String.valueOf(gst));
    }

    // Calculate Grand Total
    public void calculateGrandTotal() {
        grandtotal = totalll + gst;
   lblgrandtotal.setText(String.valueOf(grandtotal));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_time = new javax.swing.JLabel();
        l_date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtProductname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPoductprice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnADDtcart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lblgrandtotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblgst = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTotalll = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnGeneartebillp = new javax.swing.JButton();
        newcustbutton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-calendar-50.png")); // NOI18N
        jLabel1.setText("Date");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-time-48.png")); // NOI18N
        jLabel2.setText("Time");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 119, -1, -1));

        l_time.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        l_time.setText("0");
        getContentPane().add(l_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 130, 109, -1));

        l_date.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        l_date.setText("0");
        getContentPane().add(l_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 52, 109, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-billing-machine-100.png")); // NOI18N
        jLabel3.setText("BILLING PAGE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 20, -1, 72));

        jButton7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-back-24.png")); // NOI18N
        jButton7.setText("BACK TO HOME PAGE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1137, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-number-50.png")); // NOI18N
        jLabel4.setText("bill id/serial no:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 131, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setText("--");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-search-50.png")); // NOI18N
        jLabel6.setText("search");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 216, 113, -1));

        txtSearch.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 230, 173, -1));

        jTable1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 322, 467, 492));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 102, -1, -1));

        txtProductname.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        getContentPane().add(txtProductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 142, 184, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1192, 98, -1, -1));

        txtPoductprice.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        getContentPane().add(txtPoductprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1192, 138, 157, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setText("Quantity");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 194, -1, -1));

        jSpinner1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 230, 184, -1));

        txtTotal.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1193, 230, 157, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setText("Total");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1193, 194, -1, -1));

        btnClear.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-clear-50.png")); // NOI18N
        btnClear.setText("clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 276, 127, 43));

        btnADDtcart.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnADDtcart.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-add-shopping-cart-45.png")); // NOI18N
        btnADDtcart.setText("add to cart");
        btnADDtcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDtcartActionPerformed(evt);
            }
        });
        getContentPane().add(btnADDtcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1193, 276, -1, 43));

        jTable2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 337, -1, 477));

        jLabel11.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-rupees-40.png")); // NOI18N
        jLabel11.setText("GRAND TOTAL RS:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 512, -1, -1));

        lblgrandtotal.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblgrandtotal.setText("0000");
        getContentPane().add(lblgrandtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 524, -1, -1));

        jLabel13.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-file-45.png")); // NOI18N
        jLabel13.setText("GST(18%)");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 427, -1, -1));

        lblgst.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblgst.setText("0000");
        getContentPane().add(lblgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 441, -1, -1));

        jLabel15.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-rupees-40.png")); // NOI18N
        jLabel15.setText("TOTAL RS:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 347, -1, -1));

        lblTotalll.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblTotalll.setText("0000");
        getContentPane().add(lblTotalll, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 359, -1, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-food-menu-50.png")); // NOI18N
        jLabel17.setText("MENU");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 266, -1, -1));

        btnGeneartebillp.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnGeneartebillp.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-bill-60.png")); // NOI18N
        btnGeneartebillp.setText("GENERATE BILL & PRINT");
        btnGeneartebillp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneartebillpActionPerformed(evt);
            }
        });
        getContentPane().add(btnGeneartebillp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 300, 110));

        newcustbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        newcustbutton.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/wondicon-ui-free-add-user_111248.png")); // NOI18N
        newcustbutton.setText("new customer");
        newcustbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcustbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(newcustbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 683, 300, 110));

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/1600 900.jpeg")); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new datetimelive().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId=Integer.parseInt(billdoa.getId());
        jLabel5.setText(billdoa.getId());
            filterProductBYname("");
                initializeProductList(); 
        
    }//GEN-LAST:event_formComponentShown

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String name=txtSearch.getText();
        filterProductBYname(name);
     

    }//GEN-LAST:event_txtSearchKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    int index = jTable1.getSelectedRow();
    // Get the model of the table
    TableModel model = jTable1.getModel();
    // Get the product name and price from the selected row
    String productName = model.getValueAt(index, 0).toString();
    String productPrice = model.getValueAt(index, 1).toString();
    // Update the text fields with the selected product name and price
    txtProductname.setText(productName);
    txtPoductprice.setText(productPrice);
    // Set the default quantity to 1
    jSpinner1.setValue(1);
    // Calculate and set the total price based on the default quantity and product price
   
    txtTotal.setText(String.valueOf(productTotal));
    // Enable the add to cart button
    btnADDtcart.setEnabled(true);
  
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
     
        
    int quantity = (Integer) jSpinner1.getValue();
    int price = Integer.parseInt(txtPoductprice.getText());
    productTotal = price * quantity;
    txtTotal.setText(String.valueOf(productTotal));
productQuantity = quantity; 

    }//GEN-LAST:event_jSpinner1StateChanged

    private void btnADDtcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDtcartActionPerformed
        // TODO add your handling code here:
        String name=txtProductname.getText();
        String price=txtPoductprice.getText();
        String quantity=String.valueOf(jSpinner1.getValue());
        DefaultTableModel dtm=(DefaultTableModel) jTable2.getModel();
        dtm.addRow(new Object[]{name, price, quantity, productTotal});
        totalll=totalll+productTotal;
        lblTotalll.setText(String.valueOf(totalll));
      

        // Calculate GST
        calculateGST();

        // Calculate Grand Total
        calculateGrandTotal();
        
        clearProductFields();
        validatefields();
        
        
    }//GEN-LAST:event_btnADDtcartActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            clearProductFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnGeneartebillpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneartebillpActionPerformed
       SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String todayDate = dFormat.format(date);
        String TOTAL = String.valueOf(grandtotal);

        // Create a single Bill object for the entire bill
        Bill bill = new Bill();
        bill.setId(billId);
        bill.setDate(todayDate);
        // Initialize total quantity and total price variables
        int totalQuantity = 0;
        double totalPrice = 0.0;

        // Iterate through the products in the cart table (jTable2)
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String productName = model.getValueAt(i, 0).toString();
            int quantity = Integer.parseInt(model.getValueAt(i, 2).toString());
            double productPrice = Double.parseDouble(model.getValueAt(i, 1).toString());

            // Update total quantity and total price
            totalQuantity += quantity;
            totalPrice += quantity * productPrice;

            // Set product details in the Bill object
            bill.setName(productName);
            bill.setQuantity(String.valueOf(quantity));
            bill.setTotal(String.valueOf(quantity * productPrice));

            // Save the bill entry for this product
            billdoa.save(bill);
        }

    
 
    
                                            

    
    String fileName = "bill_" + billId + ".pdf"; // Unique file name based on ID
    String desktopPath = System.getProperty("user.home") + "/Desktop/Madhur/";
    File directory = new File(desktopPath);
if (!directory.exists()) {
    directory.mkdirs(); // Create directory if it doesn't exist
}

    String filePath = desktopPath + fileName;
    com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
    try {
        PdfWriter.getInstance(doc, new FileOutputStream(filePath));
        doc.open();
        Paragraph restaurantName = new Paragraph("Restaurant Management System\n");
        doc.add(restaurantName);
        Paragraph starLine = new Paragraph("****************************");
        doc.add(starLine);
        String billIdString = String.valueOf(billId);
        String grandTotalString = String.valueOf(grandtotal);

        Paragraph paragraph3 = new Paragraph("\t Bill ID: " + billIdString + "\n");

       
        for (int i = 0; i < model.getRowCount(); i++) {
           
           
            String productName = model.getValueAt(i, 0).toString();
            String quantity = model.getValueAt(i, 2).toString();
            paragraph3.add("\t Product: " + productName + ", Quantity: " + quantity + "\n");
        
        }

        paragraph3.add("\t Grand Total: " + grandTotalString + "\n");

        doc.add(paragraph3);
        doc.add(starLine);
        Paragraph thankYouParagraph = new Paragraph("\n\t Thank You, Please Visit Again!");
        doc.add(thankYouParagraph);
        doc.close();

         // Check if the file exists after saving
    File pdfFile = new File(filePath);
    if (pdfFile.exists()) {
        System.out.println("File saved successfully at: " + filePath);
        OpenPdf.openById(filePath);
    } else {
        System.err.println("Error: File does not exist at path: " + filePath);
    }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        System.err.println("Error occurred while saving the file: " + e.getMessage()); // Error message
    }


        
    }//GEN-LAST:event_btnGeneartebillpActionPerformed
 /*private int getNewBillId() {
        // Increment the lastGeneratedBillId
        lastGeneratedBillId++;

        // Return the incremented value
        return lastGeneratedBillId;
    }*/
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
      int index = jTable2.getSelectedRow();
int choice = JOptionPane.showConfirmDialog(null, "Do you want to remove this product?", "Select", JOptionPane.YES_NO_OPTION);
if (choice == JOptionPane.YES_OPTION) {
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    String total = model.getValueAt(index, 3).toString();
    int totalPrice = Integer.parseInt(total);
    grandtotal -= totalPrice; // Assuming grandTotal is a class-level variable
    lblgrandtotal.setText(String.valueOf(grandtotal));
    model.removeRow(index);
}

    }//GEN-LAST:event_jTable2MouseClicked

    private void newcustbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcustbuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new billingpage().setVisible(true);
    }//GEN-LAST:event_newcustbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billingpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDtcart;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGeneartebillp;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel l_date;
    private javax.swing.JLabel l_time;
    private javax.swing.JLabel lblTotalll;
    private javax.swing.JLabel lblgrandtotal;
    private javax.swing.JLabel lblgst;
    private javax.swing.JButton newcustbutton;
    private javax.swing.JTextField txtPoductprice;
    private javax.swing.JTextField txtProductname;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
