/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini.project.sem4;

import dataacess.billdoa;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bill;

/**
 *
 * @author madhurshinde
 */
public class mostsaledproduct extends javax.swing.JFrame {

    /**
     * Creates new form mostsaledproduct
     */
    public mostsaledproduct() {
        initComponents();
        showMostSaledProducts(); // Call method to display most saled products
    
    }
   private void showMostSaledProducts() {
    int month = jMonthChooser1.getMonth() + 1; // Month starts from 0, so add 1
    int year = jYearChooser1.getYear();

    ArrayList<Bill> mostSaledProducts = billdoa.getSumOfQuantitiesForProduct(month, year);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear the table before adding new data
    if (mostSaledProducts.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No data available for the selected month and year.");
    } else {
        for (Bill bill : mostSaledProducts) {
            Object[] row = {bill.getName(), bill.getQuantity()};
            model.addRow(row);
        }
        
        // Find the product with the highest quantity
        Bill highestQuantityProduct = mostSaledProducts.get(0);
        for (Bill bill : mostSaledProducts) {
            if (Integer.parseInt(bill.getQuantity()) > Integer.parseInt(highestQuantityProduct.getQuantity())) {
                highestQuantityProduct = bill;
            }
        }
        
        // Display the name of the product with the highest quantity in the MOSTSALED text field
        MOSTSALED.setText(highestQuantityProduct.getName());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        monthselector = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        MOSTSALED = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-back-24.png")); // NOI18N
        jButton2.setText("BACK TO HOME PAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1114, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-fast-food-40.png")); // NOI18N
        jLabel1.setText("MONTHLY ANALYSIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 524, -1));

        monthselector.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        monthselector.setText("SELECT MONTH & YEAR");
        getContentPane().add(monthselector, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, 251, 40));

        jMonthChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMonthChooser1PropertyChange(evt);
            }
        });
        getContentPane().add(jMonthChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 166, 184, 40));

        jYearChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jYearChooser1PropertyChange(evt);
            }
        });
        getContentPane().add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 166, 80, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "product_name", "quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 238, -1, 496));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setText("ITEM WITH MOST SALES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 589, 322, 48));

        MOSTSALED.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        MOSTSALED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTSALEDActionPerformed(evt);
            }
        });
        getContentPane().add(MOSTSALED, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 589, 380, 48));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/1600 900.jpeg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new datetimelive().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MOSTSALEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTSALEDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MOSTSALEDActionPerformed

    private void jMonthChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMonthChooser1PropertyChange
        // TODO add your handling code here:
        if ("month".equals(evt.getPropertyName())) {
            showMostSaledProducts();}
    }//GEN-LAST:event_jMonthChooser1PropertyChange

    private void jYearChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jYearChooser1PropertyChange
        // TODO add your handling code here:
         if ("year".equals(evt.getPropertyName())) {
            showMostSaledProducts();
        }
    }//GEN-LAST:event_jYearChooser1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mostsaledproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mostsaledproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mostsaledproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mostsaledproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mostsaledproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MOSTSALED;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel monthselector;
    // End of variables declaration//GEN-END:variables
}
