/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini.project.sem4;

import dataacess.billdoa;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bill;

/**
 *
 * @author madhurshinde
 */
public class rangedata extends javax.swing.JFrame {

    /**
     * Creates new form rangedata
     */
    public rangedata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        confirmbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        productnametxt = new javax.swing.JTextField();
        txtdate1 = new javax.swing.JTextField();
        txtdate2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-average-math-48.png")); // NOI18N
        jLabel1.setText("WEEKLY AVERAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("SELECT DATE RANGE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 188, -1, 37));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 188, 160, 37));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 188, 160, 37));

        confirmbutton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        confirmbutton.setText("confirm dates");
        confirmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 260, 188, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "product_name", "average quantity for the day"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 188, -1, 506));

        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/Madhur/icons8-back-24.png")); // NOI18N
        jButton2.setText("BACK TO HOME PAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setText("ITEM WITH MOST SALES BETWEEN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 470, 48));

        productnametxt.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        getContentPane().add(productnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 283, 48));

        txtdate1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdate1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 450, 200, 30));

        txtdate2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdate2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 200, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/madhurshinde/Desktop/1600 900.jpeg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new datetimelive().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void confirmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbuttonActionPerformed
        java.util.Date startDate = jDateChooser1.getDate();
    java.util.Date endDate = jDateChooser2.getDate();
    if (startDate == null || endDate == null) {
        JOptionPane.showMessageDialog(this, "Please select both start and end dates.");
        return;
    }
    
    ArrayList<Bill> recordsBetweenDates = billdoa.getRecordsBetweenDates(startDate, endDate);
    if (recordsBetweenDates.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No data available for the selected date range.");
        return;
    }
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear the table before adding new data
    
    int totalDays = (int)((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24)) + 1;
    
    // Create a map to store the sum of quantities for each product
    Map<String, Double> productQuantityMap = new HashMap<>();
    
    for (Bill bill : recordsBetweenDates) {
        String productName = bill.getName();
        double quantity = Double.parseDouble(bill.getQuantity());
        
        // Update the sum of quantities for the product
        productQuantityMap.put(productName, productQuantityMap.getOrDefault(productName, 0.0) + quantity);
    }
    
    // Display the product with the highest quantity
    String maxProductName = "";
    double maxQuantity = 0.0;
    for (Map.Entry<String, Double> entry : productQuantityMap.entrySet()) {
        String productName = entry.getKey();
        double totalQuantity = entry.getValue();
        double averageQuantity = totalQuantity / totalDays;
        
        Object[] row = {productName, averageQuantity};
        model.addRow(row);
        
        // Check if this product has higher quantity than the previous max
        if (totalQuantity > maxQuantity) {
            maxQuantity = totalQuantity;
            maxProductName = productName;
        }
    }
    
    // Update the labels with the start and end dates
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    txtdate1.setText("Start Date: " + sdf.format(startDate));
    txtdate2.setText("End Date: " + sdf.format(endDate));
    
    // Display the product with the highest quantity
    productnametxt.setText(maxProductName);
    }//GEN-LAST:event_confirmbuttonActionPerformed

    private void txtdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdate1ActionPerformed

    private void txtdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdate2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rangedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rangedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rangedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rangedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rangedata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmbutton;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField productnametxt;
    private javax.swing.JTextField txtdate1;
    private javax.swing.JTextField txtdate2;
    // End of variables declaration//GEN-END:variables
}
